---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: step-security/harden-runner@v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.31
        with:
          token: ${{ secrets.GITHUB_TOKEN }}